### ISSUE TITLE
send RB3011 porting patches upstream.

### ISSUE THREAD

**Issue by g6094199** [adron-s/openwrt-rb3011#1]
Hi adron-s!

Many of us cant wait to have the code upstraem to get builds on regular basis. ;-)
You put so much work and effort into this port, it would be a shame to waste it.
So would you mind to rebase to current master and do a pull request, plz!?

regards
Sash

**Comment by adron-s** [comment]
> Hi adron-s!
> 
> Many of us cant wait to have the code upstraem to get builds on regular basis. ;-)
> You put so much work and effort into this port, it would be a shame to waste it.
> So would you mind to rebase to current master and do a pull request, plz!?
> 
> regards
> Sash

Hello. Unfortunately, I don't have time for this. I hope that someone else will be able to use my work for add support of RB3011 to upstream.

**Comment by g6094199** [comment]
moving on to here: https://github.com/openwrt/openwrt/pull/4430
